### PR TITLE
sort users with matching tags

### PR DESCRIPTION
**Pull request by vabarbosa**
@lornajane for #94

### CODE REVIEW

**Comment by vabarbosa** [comment]
@ptitzler @lornajane this PR has been updated to sort by matching tags first then by name and to also include the number of tags matched as indicated in issue #94

**Comment by lornajane** [comment]
I'm struggling to test this one, since I can't add tags to the user's profile (see #113).  I tried lifting a user record from the production system and that didn't help.  Anyone else got ideas for how I should test this patch?  /cc @glynnbird

**Comment by vabarbosa** [comment]
@lornajane @ptitzler

**Comment by lornajane** [comment]
Thanks @vabarbosa, this is a neat solution.

**Pull request merged**
