### PR TITLE
hide filters and show message when user is not logged in

### PR DESCRIPTION
**Pull request by vabarbosa**
hide filters and show login instructions when user is not logged in

### CODE REVIEW

**Review by isc-rsingh — COMMENTED** [review]
Works well for the base URL. I'm seeing that if I hit a URL from my history like ./home.html#unassigned I don't get the login prompt?

**Comment by vabarbosa** [comment]
@rajrsingh `home.html` is the old UI. it should probably be removed. the new UI is just using `index.html`

**Comment by isc-rsingh** [comment]
@vabarbosa in that case it's perfect!

**Review by isc-rsingh — APPROVED** [review]

**Comment by vabarbosa** [comment]
Bluemix [toolchain](https://console-regional.ng.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console-regional.ng.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-watson-data-lab/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170906-155554 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170906-155554") to [wdp-infrastructure](https://console.bluemix.net/apps/8c899a6a-51bb-4f53-83cd-0aae75448efe?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commit dab7017cd73c155360e65cb60d1fca5c615a541e

**Pull request merged**
