### PR TITLE
issues and backlog

### PR DESCRIPTION
**Pull request by vabarbosa**
#44

### CODE REVIEW

**Comment by rajrsingh** [comment]
@vabarbosa back button works when going between #mytickets and #unassigned, but not when going from #mytickets or #unassigned back to home.html.

**Review by isc-rsingh — CHANGES_REQUESTED** [review]
@vabarbosa back button works when going between #mytickets and #unassigned, but not when going from #mytickets or #unassigned back to home.html. Is this fixable?

**Comment by vabarbosa** [comment]
@rajrsingh sorry i missed that (good catch). should be all set now if you want to update/try again

**Review by isc-rsingh — APPROVED** [review]

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/afc93986-3917-48ae-8901-f070f6d109f7 "green-blue-toolchain-20170516074606603"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/5ea1a679-3a40-49d5-9621-b48806ab22cc "green-blue-toolchain-20170516074606603") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-ptitzler_org-dev-20170609-151147 "deploy-ibm-yp-us-south-ptitzler_org-dev-20170609-151147") to [dev](https://console.ng.bluemix.net/apps/8bda6000-0f25-4803-b51a-fbce22ad52db?env_id=ibm:yp:us-south "ibm:yp:us-south:ptitzler_org:dev"), including commit 5f17ef32bd28eabca45769f7179d168b6b00a8e9

**Comment by ptitzler** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/bb9178ab-039a-4b1b-bdfa-c5ab8e217c77 "sodashboard-wdp-infra"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/592bddce-9340-4b45-9afa-14c722dd7005 "sodashboard-wdp-infra") deployed [sodashboard](https://github.com/ibm-cds-labs/sodashboard/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170609-151222 "deploy-ibm-yp-us-south-Dev-Advocates-wdp-infrastructure-20170609-151222") to [wdp-infrastructure](https://console.ng.bluemix.net/apps/9535f86f-f841-460d-94d9-7f82550f05d3?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:wdp-infrastructure"), including commit 5f17ef32bd28eabca45769f7179d168b6b00a8e9

**Pull request merged**
